### ISSUE TITLE
Menu to fix

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/ElieJosiePhotographie#1]
Heya!

Quand tu aura le temps, le menu n'est pas fonctionnel pour aller sur les autres pages (weird!) Si tu peux faire de la magie hehe! :-]

Merci!

**Comment by spectralshard** [comment]
Trouver le méchant, malheureusement, j'ai du enlever la class "scroll" de la navigation. 
Peut-tu m'enlever la bande grise qui apparait dans le menu ;-) merci!

**Comment by lorajc** [comment]
Fixed
