### ISSUE TITLE
Portfolio plugins - Mobile view

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/ElieJosiePhotographie#11]
Mettre a 100% en mobile et tablette?

![img_0389](https://cloud.githubusercontent.com/assets/11337449/12379326/6838068e-bd26-11e5-834b-ab53e06d8d3b.jpg)

![img_0408](https://cloud.githubusercontent.com/assets/11337449/12379380/79906b5a-bd27-11e5-96a1-48e757ecd1c5.jpg)

**Comment by lorajc** [comment]
Il n'est pas possible 100%, mais c'est centré
