### ISSUE TITLE
Portfolio plugins issue

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/ElieJosiePhotographie#3]
Pour le portfolio:

J'ai réussi a briser un truc (DOP!) lorsqu'on enlevé toute les photo et qu'on remet des nouvelles:
![capture d écran 2016-01-11 a 19 57 51](https://cloud.githubusercontent.com/assets/11337449/12252922/8a36ab9a-b8a9-11e5-95f6-d8f0b8e82c71.png)
(aperçu dans le backend, sur le front la page est vide)

Si on en laisse une, pas de problème pour en ajout puis l'enlever par la suite. Voir ce qu'on fait ici.

--
Est-ce possible de centré les miniatures dans l'écran, il y a un bon décalage sinon visible à droite:
![capture d ecran 2016-01-11 a 19 59 24](https://cloud.githubusercontent.com/assets/11337449/12252951/d7f4ec7a-b8a9-11e5-8127-4fc1b4e03431.png)

---
By the way: génial on peut ajouter du code html pour mettre des lien dans la description + 10 cookies
(question de possibilité)Peut-on mettre le titre et la description en dessous de l'image?
![capture d ecran 2016-01-11 a 21 02 55](https://cloud.githubusercontent.com/assets/11337449/12252962/ee8ff5ec-b8a9-11e5-8a51-34fbc413bc26.png)

Sinon le tout est vraiment génial! :D

**Comment by lorajc** [comment]
Les miniatures sont centres maintenant

**Comment by lorajc** [comment]
Je ne comprends pas l'erreur

**Comment by spectralshard** [comment]
Si on enlève toute les photo et on save, c'est la que on rogne cette erreur. Mais on va s'arranger pour pas que ça arrive! ;-)

**Comment by lorajc** [comment]
![portfolio](https://cloud.githubusercontent.com/assets/6117206/12466426/90f4bf62-bfa2-11e5-9140-e307c51b2374.PNG)

C'est centré!
