### ISSUE TITLE
Blogue

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/ElieJosiePhotographie#5]
Pour le blogue:

Si l'article a un titre plus petit, avoir moins d'espace entre le H2 et les infos.
![capture d écran 2016-01-11 a 21 01 05](https://cloud.githubusercontent.com/assets/11337449/12253049/cfa1522e-b8aa-11e5-87c7-5efff348a725.png)
--
De l'espace entre les deux article (il veut ça épuré.. on va leur donner cette sauce ;-) )
![capture d écran 2016-01-11 a 21 01 13](https://cloud.githubusercontent.com/assets/11337449/12253056/da4e3afc-b8aa-11e5-9be3-6b54ca7a9ce4.png)
--
Post list:
On va mettre 5 par pages pour le moment, vu qu'il va y avoir de bonne photos et la page actif en primary à la place de noir.  

![capture d ecran 2016-01-11 a 21 55 55](https://cloud.githubusercontent.com/assets/11337449/12253533/46b37236-b8ae-11e5-88c7-a710269e3562.png)

---

Mobile:
Placement des éléments:
Row: Date (6col) avec User (6col)
Row: Catégories
![capture d ecran 2016-01-11 a 21 05 53](https://cloud.githubusercontent.com/assets/11337449/12253210/2835ce00-b8ac-11e5-92b1-425bcf8f6ed4.png)

Merci!

**Comment by lorajc** [comment]
Done!
