### ISSUE TITLE
Blogue Article

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/ElieJosiePhotographie#6]
Pour les articles:
Mobile:
Espace en superflue après le titre de article
Placement des éléments:
Row: Date avec User
Row: Catégories
Row: social media (un a la suite de l'autre? sinon espace entre les blocs ?)
![capture d écran 2016-01-11 a 21 06 11](https://cloud.githubusercontent.com/assets/11337449/12253140/9b95fea2-b8ab-11e5-8194-356d668a0cf7.png)

---

Il ne manque que le plugin Disqus (je t'es envoyer les infos) et bouton retour vers le blogue :)

![capture d écran 2016-01-11 a 21 03 52](https://cloud.githubusercontent.com/assets/11337449/12253091/1d3361d0-b8ab-11e5-900c-23b01c631f78.png)

**Comment by spectralshard** [comment]
Fix the two row:
Row: Date avec User
Row: Catégories

Got a issue in article regarding social widget, we can scroll/slide to the right! <-not good!

**Comment by lorajc** [comment]
Blog fixed!

**Comment by lorajc** [comment]
Disqus not installed yet

**Comment by spectralshard** [comment]
Okay, I have send you the url http://eliejosiephotographie.com

**Comment by lorajc** [comment]
Done!
